// SECTORS
SECTORS["BRYC"] = "Bryyo: Cliffside"
SECTORS["BRYF"] = "Bryyo: Fiery"
SECTORS["BRYI"] = "Bryyo: Ice"
SECTORS["BRYS"] = "Bryyo: Seed"
SECTORS["BRYT"] = "Bryyo: Thorn Jungle"
SECTORS["GFSO"] = "GFS Olympus"
SECTORS["GFSV"] = "GFS Valhalla"
SECTORS["SKYE"] = "Elysia: SkyTown East"
SECTORS["SKYW"] = "Elysia: SkyTown West"
SECTORS["ELYS"] = "Elysia: Seed"
SECTORS["NORI"] = "Norion"
SECTORS["PHCC"] = "Pirate Homeworld: Command Center"
SECTORS["PHMS"] = "Pirate Homeworld: Mining Site"
SECTORS["PHRF"] = "Pirate Homeworld: Research Facility"
SECTORS["PHSD"] = "Pirate Homeworld: Seed"

//       "ID"         , "alias-to"   , "reward"                     , "sect", "location"               , "title"                              , "details"
addTask( "ME"         , null         , null                         , null  , null                     , "Missile Expansions"                 , null                                 )
addTask( "ME/01"      , null         , "Missile Expansion 01"       , "GFSO", "Munitions Storage"      , null                                 , null                                 )
addTask( "ME/02"      , null         , "Missile Expansion 02"       , "NORI", "Cargo Hub"              , null                                 , null                                 )
addTask( "ME/03"      , null         , "Missile Expansion 03"       , "BRYC", "Grand Court Path"       , null                                 , null                                 )
addTask( "ME/04"      , null         , "Missile Expansion 04"       , "BRYC", "Hillside Vista"         , null                                 , null                                 )
addTask( "ME/05"      , null         , "Missile Expansion 05"       , "BRYF", "Main Lift"              , null                                 , null                                 )
addTask( "ME/06"      , null         , "Missile Expansion 06"       , "BRYF", "Gel Hall"               , null                                 , null                                 )
addTask( "ME/07"      , null         , "Missile Expansion 07"       , "BRYF", "Gel Hall"               , null                                 , null                                 )
addTask( "ME/08"      , null         , "Missile Expansion 08"       , "BRYF", "Gel Refinery Site"      , null                                 , null                                 )
addTask( "ME/09"      , null         , "Missile Expansion 09"       , "BRYC", "Crash Site"             , null                                 , null                                 )
addTask( "ME/10"      , null         , "Missile Expansion 10"       , "BRYT", "Jungle Generator"       , null                                 , null                                 )
addTask( "ME/11"      , null         , "Missile Expansion 11"       , "BRYT", "Generator Hall North"   , null                                 , null                                 )
addTask( "ME/12"      , null         , "Missile Expansion 12"       , "SKYW", "Transit Hub"            , null                                 , null                                 )
addTask( "ME/13"      , null         , "Missile Expansion 13"       , "SKYW", "Barracks Access"        , null                                 , null                                 )
addTask( "ME/14"      , null         , "Missile Expansion 14"       , "SKYW", "Skybridge Hera"         , null                                 , null                                 )
addTask( "ME/15"      , null         , "Missile Expansion 15"       , "SKYW", "Main Docking Bay"       , null                                 , null                                 )
addTask( "ME/16"      , null         , "Missile Expansion 16"       , "BRYF", "Imperial Hall"          , null                                 , null                                 )
addTask( "ME/17"      , null         , "Missile Expansion 17"       , "SKYE", "Gearworks"              , null                                 , null                                 )
addTask( "ME/18"      , null         , "Missile Expansion 18"       , "SKYE", "Botanica"               , null                                 , null                                 )
addTask( "ME/19"      , null         , "Missile Expansion 19"       , "SKYE", "Concourse"              , null                                 , null                                 )
addTask( "ME/20"      , null         , "Missile Expansion 20"       , "PHCC", "Command Courtyard"      , null                                 , null                                 )
addTask( "ME/21"      , null         , "Missile Expansion 21"       , "PHCC", "Command Station"        , null                                 , null                                 )
addTask( "ME/22"      , null         , "Missile Expansion 22"       , "PHCC", "Security Air Lock"      , null                                 , null                                 )
addTask( "ME/23"      , null         , "Missile Expansion 23"       , "PHRF", "Scrapvault"             , null                                 , null                                 )
addTask( "ME/24"      , null         , "Missile Expansion 24"       , "PHRF", "Metroid Processing"     , null                                 , null                                 )
addTask( "ME/25"      , null         , "Missile Expansion 25"       , "PHRF", "Creche Transit"         , null                                 , null                                 )
addTask( "ME/26"      , null         , "Missile Expansion 26"       , "SKYW", "Powerworks"             , null                                 , null                                 )
addTask( "ME/27"      , null         , "Missile Expansion 27"       , "SKYW", "Construction Bay"       , null                                 , null                                 )
addTask( "ME/28"      , null         , "Missile Expansion 28"       , "SKYW", "Steambot Barracks"      , null                                 , null                                 )
addTask( "ME/29"      , null         , "Missile Expansion 29"       , "SKYE", "Concourse Ventilation"  , null                                 , null                                 )
addTask( "ME/30"      , null         , "Missile Expansion 30"       , "PHRF", "Craneyard"              , null                                 , null                                 )
addTask( "ME/31"      , null         , "Missile Expansion 31"       , "PHMS", "Phazon Quarry"          , null                                 , null                                 )
addTask( "ME/32"      , null         , "Missile Expansion 32"       , "PHMS", "Phazon Mine Entry"      , null                                 , null                                 )
addTask( "ME/33"      , null         , "Missile Expansion 33"       , "NORI", "Cargo Dock A"           , null                                 , null                                 )
addTask( "ME/34"      , null         , "Missile Expansion 34"       , "NORI", "Maintenance Station"    , null                                 , null                                 )
addTask( "ME/35"      , null         , "Missile Expansion 35"       , "NORI", "Substation West"        , null                                 , null                                 )
addTask( "ME/36"      , null         , "Missile Expansion 36"       , "NORI", "Docking Hub Alpha"      , null                                 , null                                 )
addTask( "ME/37"      , null         , "Missile Expansion 37"       , "BRYF", "Temple of Bryyo"        , null                                 , null                                 )
addTask( "ME/38"      , null         , "Missile Expansion 38"       , "BRYC", "Hall  of Golems"        , null                                 , null                                 )
addTask( "ME/39"      , null         , "Missile Expansion 39"       , "BRYC", "Burrow"                 , null                                 , null                                 )
addTask( "ME/40"      , null         , "Missile Expansion 40"       , "BRYC", "Fuel Gel Pool"          , null                                 , null                                 )
addTask( "ME/41"      , null         , "Missile Expansion 41"       , "BRYC", "Fuel Gel Pool"          , null                                 , null                                 )
addTask( "ME/42"      , null         , "Missile Expansion 42"       , "BRYT", "Ancient Courtyard"      , null                                 , null                                 )
addTask( "ME/43"      , null         , "Missile Expansion 43"       , "BRYC", "Hidden Court"           , null                                 , null                                 )
addTask( "ME/44"      , null         , "Missile Expansion 44"       , "BRYC", "Falls of Fire"          , null                                 , null                                 )
addTask( "ME/45"      , null         , "Missile Expansion 45"       , "BRYC", "Reliquary III"          , null                                 , null                                 )
addTask( "ME/46"      , null         , "Missile Expansion 46"       , "BRYC", "Gateway"                , null                                 , null                                 )
addTask( "ME/47"      , null         , "Missile Expansion 47"       , "GFSV", "Weapons Cache"          , null                                 , null                                 )
addTask( "ME/48"      , null         , "Missile Expansion 48"       , "GFSV", "Auxiliary Lift"         , null                                 , null                                 )
addTask( "ME/49"      , null         , "Missile Expansion 49"       , "GFSV", "Medlab Alpha"           , null                                 , null                                 )
addTask( "ME/50"      , null         , "Missile Expansion 50"       , "PHCC", "Lift Hub"               , null                                 , null                                 )
addTask( "ME/51"      , null         , "Missile Expansion 51"       , "PHCC", "Flux Control"           , null                                 , null                                 )
//       "ID"         , "alias-to"   , "reward"                     , "sect", "location"               , "title"                              , "details"
addTask( "ET"         , null         , null                         , null  , null                     , "Energy Tanks"                       , null                                 )
addTask( "ET/01"      , null         , "Energy Tank 01"             , "GFSO", "Ventilation Shaft"      , null                                 , null                                 )
addTask( "ET/02"      , null         , "Energy Tank 02"             , "NORI", "Substation East"        , null                                 , null                                 )
addTask( "ET/03"      , null         , "Energy Tank 03"             , "BRYC", "Reliquary II"           , null                                 , null                                 )
addTask( "ET/04"      , null         , "Energy Tank 04"             , "BRYC", "Ruined Shrine"          , null                                 , null                                 )
addTask( "ET/05"      , null         , "Energy Tank 05"             , "BRYT", "Vault"                  , null                                 , null                                 )
addTask( "ET/06"      , null         , "Energy Tank 06"             , "SKYW", "Steambot Barracks"      , null                                 , null                                 )
addTask( "ET/07"      , null         , "Energy Tank 07"             , "SKYW", "Arrival Station"        , null                                 , null                                 )
addTask( "ET/08"      , null         , "Energy Tank 08"             , "SKYE", "Xenoresearch A Lift"    , null                                 , null                                 )
addTask( "ET/09"      , null         , "Energy Tank 09"             , "PHRF", "Scrapworks"             , null                                 , null                                 )
addTask( "ET/10"      , null         , "Energy Tank 10"             , "SKYW", "Zipline Station Charlie", null                                 , null                                 )
addTask( "ET/11"      , null         , "Energy Tank 11"             , "PHRF", "Metroid Creche"         , null                                 , null                                 )
addTask( "ET/12"      , null         , "Energy Tank 12"             , "BRYI", "Tower"                  , null                                 , null                                 )
addTask( "ET/13"      , null         , "Energy Tank 13"             , "BRYC", "Machineworks Bridge"    , null                                 , null                                 )
addTask( "ET/14"      , null         , "Energy Tank 14"             , "GFSV", "Munitions Locker"       , null                                 , null                                 )
//       "ID"         , "alias-to"   , "reward"                     , "sect", "location"               , "title"                              , "details"
addTask( "EC"         , null         , null                         , null  , null                     , "Energy Cells"                       , null                                 )
addTask( "EC/1"       , null         , "Energy Cell 1"              , "BRYC", "Federation Landing Site", null                                 , null                                 )
addTask( "EC/2"       , null         , "Energy Cell 2"              , "SKYE", "Xenoresearch B"         , null                                 , null                                 )
addTask( "EC/3"       , null         , "Energy Cell 3"              , "PHCC", "Command Courtyard"      , null                                 , null                                 )
addTask( "EC/4"       , null         , "Energy Cell 4"              , "PHRF", "Metroid Processing"     , null                                 , null                                 )
addTask( "EC/5"       , null         , "Energy Cell 5"              , "SKYW", "Ballista Storage"       , null                                 , null                                 )
addTask( "EC/6"       , null         , "Energy Cell 6"              , "PHMS", "Phazon Quarry"          , null                                 , null                                 )
addTask( "EC/7"       , null         , "Energy Cell 7"              , "NORI", "Generator B"            , null                                 , null                                 )
addTask( "EC/8"       , null         , "Energy Cell 8"              , "BRYC", "Hidden Court"           , null                                 , null                                 )
addTask( "EC/9"       , null         , "Energy Cell 9"              , "GFSV", "Docking bay 5"          , null                                 , null                                 )
//       "ID"         , "alias-to"   , "reward"                     , "sect", "location"               , "title"                              , "details"
addTask( "GME"        , null         , null                         , null  , null                     , "Gunship Missile Expansions"         , null                                 )
addTask( "GME/1"      , null         , "Gunship Missile Expansion 1", "BRYC", "Federation Landing Site", null                                 , null                                 )
addTask( "GME/2"      , null         , "Gunship Missile Expansion 2", "BRYT", "Auxiliary Dynamo"       , null                                 , null                                 )
addTask( "GME/3"      , null         , "Gunship Missile Expansion 3", "SKYW", "Security Station"       , null                                 , null                                 )
addTask( "GME/4"      , null         , "Gunship Missile Expansion 4", "BRYI", "Hall of Remembrance"    , null                                 , null                                 )
addTask( "GME/5"      , null         , "Gunship Missile Expansion 5", "SKYW", "Hoverplat Docking Site" , null                                 , null                                 )
addTask( "GME/6"      , null         , "Gunship Missile Expansion 6", "BRYC", "Colossus Vista"         , null                                 , null                                 )
addTask( "GME/7"      , null         , "Gunship Missile Expansion 7", "GFSV", "Xenoresearch Lab"       , null                                 , null                                 )
addTask( "GME/8"      , null         , "Gunship Missile Expansion 8", "PHRF", "Scrapworks"             , null                                 , null                                 )
addTask( "GME/9"      , null         , "Gunship Missile Expansion 9", "PHRF", "Processing Access"      , null                                 , null                                 )
//       "ID"         , "alias-to"   , "reward"                     , "sect", "location"               , "title"                              , "details"
addTask( "SU"         , null         , null                         , null  , null                     , "Suit Upgrades"                      , null                                 )
addTask( "SU/Lasso"   , null         , "Grapple Lasso"              , "NORI", "Docking Hub Alpha"      , null                                 , null                                 )
addTask( "SU/Ped"     , null         , "Phazon Enhancement Device"  , "GFSO", "Medlab Delta"           , null                                 , null                                 )
addTask( "SU/Swing"   , null         , "Grapple Swing"              , "BRYC", "Reliquary I"            , null                                 , null                                 )
addTask( "SU/IceMiss" , null         , "Ice Missiles"               , "BRYF", "Temple of Bryyo"        , null                                 , null                                 )
addTask( "SU/HypBall" , null         , "Hyper Ball"                 , "BRYS", "Leviathan Core"         , null                                 , null                                 )
addTask( "SU/BooBall" , null         , "Boost Ball"                 , "SKYW", "Ballista Storage"       , null                                 , null                                 )
addTask( "SU/Plasma"  , null         , "Plasma Beam"                , "SKYW", "Main Docking Bay"       , null                                 , null                                 )
addTask( "SU/Screw"   , null         , "Screw Attack"               , "BRYI", "Hall of Remembrance"    , null                                 , null                                 )
addTask( "SU/ShipGrap", null         , "Ship Grapple"               , "SKYE", "Landing Site B"         , null                                 , null                                 )
addTask( "SU/SeekMiss", null         , "Seeker Missile"             , "SKYE", "Xenoresearch B"         , null                                 , null                                 )
addTask( "SU/HypMiss" , null         , "Hyper Missile"              , "ELYS", "Leviathan Core"         , null                                 , null                                 )
addTask( "SU/XRay"    , null         , "X-Ray Visor"                , "PHCC", "Command Vault"          , null                                 , null                                 )
addTask( "SU/GrapAmp" , null         , "Grapple Amp"                , "PHRF", "Proving Grounds"        , null                                 , null                                 )
addTask( "SU/SpiBall" , null         , "Spider Ball"                , "SKYW", "Powerworks"             , null                                 , null                                 )
addTask( "SU/HazShld" , null         , "Hazard Shield"              , "PHRF", "Craneyard"              , null                                 , null                                 )
addTask( "SU/Nova"    , null         , "Nova Beam"                  , "PHMS", "Main Cavern"            , null                                 , null                                 )
addTask( "SU/HypGrap" , null         , "Hyper Grapple"              , "PHSD", "Leviathan Core"         , null                                 , null                                 )
//       "ID"         , "alias-to"   , "reward"                     , "sect", "location"               , "title"                              , "details"
addTask( "AC"         , null         , null                         , null  , null                     , "All Pickups (Chronological)"        , null                                 )
addTask( "AC/1"       , null         , null                         , "GFSO", null                     , "GFS Olympus"                        , null                                 )
addTask( "AC/1/1"     , "ET/01"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/1/2"     , "ME/01"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/2"       , null         , null                         , "NORI", null                     , "Norion"                             , null                                 )
addTask( "AC/2/1"     , "SU/Lasso"   , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/2/2"     , "ME/02"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/2/3"     , "ET/02"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/3"       , null         , null                         , "GFSO", null                     , "GFS Olympus"                        , null                                 )
addTask( "AC/3/1"     , "SU/Ped"     , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/4"       , null         , null                         , "BRYC", null                     , "Bryyo: Cliffside"                   , null                                 )
addTask( "AC/4/1"     , "ET/03"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/4/2"     , "ME/03"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/4/3"     , "ME/04"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/4/4"     , "SU/Swing"   , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/5"       , null         , null                         , "BRYF", null                     , "Bryyo: Fiery"                       , null                                 )
addTask( "AC/5/1"     , "ME/05"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/5/2"     , "ME/06"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/5/3"     , "SU/IceMiss" , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/5/4"     , "ME/07"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/5/5"     , "ME/08"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/6"       , null         , null                         , "BRYC", null                     , "Bryyo: Cliffside"                   , null                                 )
addTask( "AC/6/1"     , "ME/09"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/6/2"     , "ET/04"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/6/3"     , "EC/1"       , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/6/4"     , "GME/1"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/7"       , null         , null                         , "BRYT", null                     , "Bryyo: Thorn Jungle"                , null                                 )
addTask( "AC/7/1"     , "ET/05"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/7/2"     , "ME/10"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/7/3"     , "GME/2"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/7/4"     , "ME/11"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/8"       , null         , null                         , "BRYS", null                     , "Bryyo: Seed"                        , null                                 )
addTask( "AC/8/1"     , "SU/HypBall" , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/9"       , null         , null                         , "SKYW", null                     , "Elysia: SkyTown West"               , null                                 )
addTask( "AC/9/1"     , "ME/12"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/9/2"     , "ME/13"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/9/3"     , "ET/06"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/9/4"     , "ME/14"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/9/5"     , "SU/BooBall" , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/9/6"     , "ET/07"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/9/7"     , "SU/Plasma"  , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/9/8"     , "ME/15"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/9/9"     , "GME/3"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/10"      , null         , null                         , "BRYF", null                     , "Bryyo: Fiery"                       , null                                 )
addTask( "AC/10/1"    , "ME/16"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/11"      , null         , null                         , "BRYI", null                     , "Bryyo: Ice"                         , null                                 )
addTask( "AC/11/1"    , "SU/Screw"   , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/11/2"    , "GME/4"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/12"      , null         , null                         , "SKYE", null                     , "Elysia: SkyTown East"               , null                                 )
addTask( "AC/12/1"    , "SU/ShipGrap", null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/12/2"    , "ME/17"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/12/3"    , "ME/18"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/12/4"    , "EC/2"       , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/12/5"    , "SU/SeekMiss", null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/12/6"    , "ET/08"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/12/7"    , "ME/19"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/13"      , null         , null                         , "ELYS", null                     , "Elysia: Seed"                       , null                                 )
addTask( "AC/13/1"    , "SU/HypMiss" , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/14"      , null         , null                         , "PHCC", null                     , "Pirate Homeworld: Command Center"   , null                                 )
addTask( "AC/14/1"    , "ME/20"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/14/2"    , "EC/3"       , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/14/3"    , "ME/21"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/14/4"    , "SU/XRay"    , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/14/5"    , "ME/22"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/15"      , null         , null                         , "PHRF", null                     , "Pirate Homeworld: Research Facility", null                                 )
addTask( "AC/15/1"    , "ME/23"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/15/2"    , "ET/09"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/15/3"    , "EC/4"       , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/15/4"    , "ME/24"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/15/5"    , "ME/25"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/15/6"    , "SU/GrapAmp" , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/16"      , null         , null                         , "SKYW", null                     , "Elysia: SkyTown West"               , null                                 )
addTask( "AC/16/1"    , "SU/SpiBall" , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/16/2"    , "ME/26"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/16/3"    , "ET/10"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/16/4"    , "ME/27"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/16/5"    , "EC/5"       , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/16/6"    , "GME/5"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/16/7"    , "ME/28"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/17"      , null         , null                         , "SKYE", null                     , "Elysia: SkyTown East"               , null                                 )
addTask( "AC/17/1"    , "ME/29"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/18"      , null         , null                         , "PHRF", null                     , "Pirate Homeworld: Research Facility", null                                 )
addTask( "AC/18/1"    , "ME/30"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/18/2"    , "SU/HazShld" , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/18/3"    , "ET/11"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/19"      , null         , null                         , "PHMS", null                     , null                                 , null                                 )
addTask( "AC/19/1"    , "ME/31"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/19/2"    , "SU/Nova"    , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/19/3"    , "EC/6"       , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/19/4"    , "ME/32"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/20"      , null         , null                         , "NORI", null                     ,"Norion"                              , null                                 )
addTask( "AC/20/1"    , "ME/33"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/20/2"    , "ME/34"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/20/3"    , "ME/35"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/20/4"    , "EC/7"       , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/20/5"    , "ME/36"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/21"      , null         , null                         , "BRYF", null                     , "Bryyo: Fiery"                       , null                                 )
addTask( "AC/21/1"    , "ME/37"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/22"      , null         , null                         , "BRYI", null                     , "Bryyo: Ice"                         , null                                 )
addTask( "AC/22/2"    , "ET/12"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/23"      , null         , null                         , "BRYC", null                     , "Bryyo: Cliffside"                   , null                                 )
addTask( "AC/23/1"    , "ME/38"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/23/2"    , "ME/39"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/23/3"    , "ME/40"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/23/4"    , "ME/41"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/23/5"    , "GME/6"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/23/6"    , "ET/13"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/24"      , null         , null                         , "BRYT", null                     , "Bryyo: Thorn Jungle"                , null                                 )
addTask( "AC/24/1"    , "ME/42"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/25"      , null         , null                         , "BRYC", null                     , "Bryyo: Cliffside"                   , null                                 )
addTask( "AC/25/1"    , "ME/43"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/25/2"    , "EC/8"       , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/25/3"    , "ME/44"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/25/4"    , "ME/45"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/25/5"    , "ME/46"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/26"      , null         , null                         , "GFSV", null                     , "GFS Valhalla"                       , null                                 )
addTask( "AC/26/1"    , "EC/9"       , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/26/2"    , "ME/47"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/26/3"    , "ME/48"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/26/4"    , "GME/7"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/26/5"    , "ME/49"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/26/6"    , "ET/14"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/27"      , null         , null                         , "PHCC", null                     , "Pirate Homeworld: Command Center"   , null                                 )
addTask( "AC/27/1"    , "ME/50"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/27/2"    , "ME/51"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/28"      , null         , null                         , "PHRF", null                     , "Pirate Homeworld: Research Facility", null                                 )
addTask( "AC/28/1"    , "GME/8"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/28/2"    , "GME/9"      , null                         , null  , null                     , null                                 , null                                 )
addTask( "AC/29"      , null         , null                         , "PHSD", null                     , "Pirate Homeworld: Seed"             , null                                 )
addTask( "AC/29/1"    , "SU/HypGrap" , null                         , null  , null                     , null                                 , null                                 )
//       "ID"         , "alias-to"   , "reward"                     , "sect", "location"               , "title"                              , "details"
addTask( "ABT"        , null         , null                         , null  , null                     , "All Pickups (By Type)"              , null                                 )
addTask( "ABT/ME"     , "ME"         , null                         , null  , null                     , null                                 , null                                 )
addTask( "ABT/ET"     , "ET"         , null                         , null  , null                     , null                                 , null                                 )
addTask( "ABT/EC"     , "EC"         , null                         , null  , null                     , null                                 , null                                 )
addTask( "ABT/GME"    , "GME"        , null                         , null  , null                     , null                                 , null                                 )
addTask( "ABT/SU"     , "SU"         , null                         , null  , null                     , null                                 , null                                 )
